### ISSUE TITLE
Sync launching prevents Node timers from firing

### ISSUE THREAD

**Issue by guigrpa** [mrkmg/node-external-editor#1]
Launching the external editor synchronously prevents Node timers (set via `setTimeout`, `setInterval`) to fire for as long as the editor remains open. Even if, as stated in the *readme*, this is not so important in interactive applications, even those applications may have background processes (requiring no stdin/stdout access whatsoever) that are interrupted.

Is there any plan to change this?

See also https://github.com/SBoudrias/Inquirer.js/issues/418

**Comment by mrkmg** [comment]
I will look into this, and try finding a work around again. I wrote this initially as async, but ran into problems...

**Comment by guigrpa** [comment]
Thanks in advance!
