### ISSUE TITLE
Allow analysis of editor's exit code

### ISSUE THREAD

**Issue by ivangreene** [mrkmg/node-external-editor#15]
Some editors have an option to exit with a nonzero code to signal that edits made should be disregarded by the program expecting them (e.g.: `:cq` in Vim exits the program with `1`).
It would be nice to be able to handle this code. Maybe `.edit()` could return a number instead of a string if the editor exits with a nonzero code? The code will be returned in the object from spawnSync as `status`. I'm happy to work on this, let me know if you have any implementation ideas.

**Comment by mrkmg** [comment]
Added the ability to check the last exit status in v2.2.0
