### ISSUE TITLE
Invalid encoding for iconv-lite

### ISSUE THREAD

**Issue by doowb** [mrkmg/node-external-editor#16]
Hi,

I'm having an issue because sometimes an encoding comes back that's not compatible with [iconv-lite](https://github.com/ashtuchkin/iconv-lite).

I'm using `vim` on mac for the editor and I get the following encodings for the following strings

- `hi\n` => `UTF-32LE`
- `hi\n\n` => `UTF-8`
- `hi this is a longer string\n` => `ISO-8859-1`

I opened [this issue](https://github.com/runk/node-chardet/issues/15) on `chardet` since I'm not sure the best place this should be fixed. I haven't looked, but if `iconv-lite` provides a way to check supported encodings before using them, it might be a good addition here.

**Comment by mrkmg** [comment]
I am looking into how to deal with this issue.
