### ISSUE TITLE
Unable to open it with Notepad++

### ISSUE THREAD

**Issue by ManadayM** [mrkmg/node-external-editor#17]
Firstly this won't fit in the Issue category since I'm seeking someone's help, so kind apology in the first place.

Coming to the point, I want to open notepad++ instead notepad to offer my CLI users to edit the JSON based configuration through text-editor. Notepad is horribly formatting my JSON string but if I copy & paste the same text content to any other editor (Notepad++, VSCode) the content looks neat. Could anyone please guide me what is the right way to set `EDITOR` environment value for Notepad++?

I tried setting it as follows with no luck 
1. `$ EDITOR=notepad++ node app tool-builder`
2. `$ EDITOR="C:\Program Files (x86)\Notepad++\notepad++.exe" node app tool-builder`

PS - I'm using Inquirer.js with a question having `editor` prompt. Not using this module directly but I found Inquirer uses this module and hence I pestering here.

**Comment by mrkmg** [comment]
Hmmm. I have never tried the module with notepad++.

I am looking at the possibility now.

**Comment by mrkmg** [comment]
I have found the problem. It is due to spaces in the path of the editor. In your case, the space in "Program Files (x86)" is causing the problem. I am investigating possible solutions to this issue.

**Comment by mrkmg** [comment]
I have just pushed an update which should solve the issue you are having, but you will have to escape the spaces in your "EDITOR" variable.

Try the following:

```
EDITOR="C:\Program\ Files\ (x86)\Notepad++\notepad++.exe -nosession" node app tool-builder
```

From my testing with Notepad++, you need to pass the "-nosession" parameter to ensure that it creates a new session and does not launch into an already open window and exit immediately.

You will likely need to `npm install` again to get the newest release (3.0.1) of external-editor.

**Comment by ManadayM** [comment]
Thank you for your time and efforts @mrkmg ! I followed your suggestion exactly as you described (including "-nosession" part) and also tweaked it in few other ways and editors (Notepad++ and VS Code) to make it run. Although as soon as I hit enter the it just gets terminated. This doesn't happen with notepad. Looks like I'm still making some silly mistake.

![external-editor](https://user-images.githubusercontent.com/521134/43999739-54da4710-9e0a-11e8-9917-bfcbe0e4b206.gif)

**Comment by GenieTim** [comment]
@ManadayM : it is quite some time ago, but if you are still wondering, I guess I found the solution: similar to the way on [how to set VSCode to be git's editor,](https://stackoverflow.com/questions/30024353/how-to-use-visual-studio-code-as-default-editor-for-git) you have to do the analog here: set `export EDITOR="vscode --wait".`
