### ISSUE TITLE
Can we set a custom extension ?

### ISSUE THREAD

**Issue by lefuturiste** [mrkmg/node-external-editor#19]
It's would be nice to choose a custom extension, for example .json or .yml to get syntax colors in the editor.

Let me known if this is already inplemented. If not, I will be happy to work on this new feature and submit it via PR.

**Comment by mrkmg** [comment]
Currently, the implementation is extremely simple with no options other than the text you want to edit. It could be nice to have some options. For example: filename, file extension, temp path override, etc. I will see what I can come up with that is backwards compatible.

**Comment by mrkmg** [comment]
The new release, 3.1.0, allows for options to be provided for the temporary file.

**Comment by lefuturiste** [comment]
thx!
