### ISSUE TITLE
Inline `temp.path`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [mrkmg/node-external-editor#2]
`node-external-editor` has `temp` as a dependency, but it only uses one function, `temp.path`.  This can be inlined as
```
// Used for consistent temp location in Node 0.10.
var osTmpdir = require('os-tmpdir');

// Instead of temp.path
function tempPath() {
  var now = new Date();
  // Random filename
  var name = [now.getYear(), now.getMonth(), now.getDate(),'-',process.pid,'-',(Math.random() * 0x100000000 + 1).toString(36)].join('');
  return path.join(path.resolve(osTmpdir()), name);
};
```
or
```
// Will go to 'c:\\windows\\temp' in Windows for Node 0.10 and under.
var tmpdir = require('os').tmpdir;

// Instead of temp.path
function tempPath() {
  var now = new Date();
  // Random filename
  var name = [now.getYear(), now.getMonth(), now.getDate(),'-',process.pid,'-',(Math.random() * 0x100000000 + 1).toString(36)].join('');
  return path.join(path.resolve(tmpdir()), name);
}
```
Coffeescript isn't my best language, but I think it'd be something like
```
tmpdir = require('os').tmpr

tempPath: =>
  @now = new Date()
  @name = [@now.getYear(), @now.getMonth(), @now.getDate(), '-', process.pid, '-', (Math.random() * 0x100000000 + 1).toString(36)].join('')
  path.join(path.resolve(tmpdir()), name)
```
Anyway, it'd save 30 some KB off the NPM package.

**Comment by mrkmg** [comment]
Nice catch, I will investigate this.

Aside from saving another package, are there any other reasons not to use the temp package?

**Comment by wtgtybhertgeghgtwtg** [comment]
[It might not be maintained](https://github.com/bruce/node-temp/issues/58) and [it's pinned to an older version of `rimraf`](https://github.com/bruce/node-temp/blob/master/package.json#L25), but that's about it.  Admittedly, these aren't the best reasons to drop a dependency, but it's your call.
