### ISSUE TITLE
chid_process implicit dependency

### ISSUE THREAD

**Issue by Oaxoa** [mrkmg/node-external-editor#20]
in main.js you have the following:
var child_process_1 = require("child_process");

child_process is not an internal file but a dependency.
This dependency is:
* not listed in the package.json
* broken and replaced with some placeholder package.

Any idea how shall I circumvent this?
I am not using external-editor directly but through the Storybook dependency tree.
Ty

**Comment by jaredly** [comment]
@Oaxoa `child_process` is a [built-in node module](https://nodejs.org/api/child_process.html). If you're using this package `node-external-editor` outside of node (e.g. with webpack/browserify/parcel etc.), then you'll run into troubles.
