### ISSUE TITLE
String encoding

### ISSUE THREAD

**Issue by Equim-chan** [mrkmg/node-external-editor#7]
The problem is, maybe the called editor has a non-UTF8 preference, then `toString()` may fail into mojibake.

https://github.com/mrkmg/node-external-editor/blob/master/src/index.coffee#L86

**Comment by mrkmg** [comment]
I am not sure how to handle that.

I see https://www.npmjs.com/package/detect-character-encoding, but this module states in it's readme it's not supported in 32-bit or windows environments. 

Do you know of a way to reliably detect the encoding of a file?

**Comment by Equim-chan** [comment]
I would recommend [this module](https://nodei.co/npm/jschardet/).

**Comment by Equim-chan** [comment]
I wish I could help but sadly I can't do CoffeeScript. Here is an example in JavaScript:
```js
const unknownEncoded = fs.readFileSync('./testencoding.txt');
const originEncoding = jschardet.detect(unknownEncoded).encoding;
const utf8Encoded = iconv.decode(unknownEncoded, originEncoding);
console.log(unknownEncoded);
console.log('origin encode:', originEncoding);
console.log('utf8 encoded:\n', utf8Encoded);
```
```
<Buffer d5 e2 b8 f6 ce c4 bc fe bb e1 b2 e2 ca d4 65 6e 63 6f 64 69 6e 67 b5 c4 bc ec b2 e2 cb ae c6 bd a1 a3 0d 0a 54 68 69 73 20 66 69 6c 65 20 69 73 20 65 ... >
origin encode: GB2312
utf8 encoded:
 这个文件会测试encoding的检测水平。
This file is encoded in GB2312.
换行。
```

**Comment by mrkmg** [comment]
I have implemented your selection. Should be launched shortly.
