### ISSUE TITLE
jschardet under dev-dependencies

### ISSUE THREAD

**Issue by cynthiax** [mrkmg/node-external-editor#9]
Can we have jschardet under dev-dependencies instead of dependencies?

We are pulling node-external-editor as part of the eslint chain in a corporate environment where LGPL licensed software can't be used. Currently jschardet is under LGPL license and this is blocking us right now.

**Comment by mrkmg** [comment]
I can not move jschardet to dev as it is used at runtime.

If you know of alternative library which provides the same functionality, I would be open to implementing it.

**Comment by loganrosen** [comment]
I found these two libraries, which are both based on [ICU](http://site.icu-project.org/) (which has a less restrictive license):
- https://github.com/runk/node-chardet
- https://github.com/sonicdoe/detect-character-encoding

I can't vouch for either of them though. Haven't used them. But they seem to provide the same functionality.

**Comment by mrkmg** [comment]
This is good news, I am always open to less restrictive licenses.

I will take a look at both of them.

**Comment by delfrrr** [comment]
+1 for dropping `jschardet`

**Comment by mrkmg** [comment]
Testing the alternatives now.
